/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/eventos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Eventos entre dos fechas, de un polo o de todos
         * @description Los del calendario oficial y los que publicaron los municipios (`fuente: "publicado"`).
         */
        get: operations["eventos_v1_eventos_get"];
        put?: never;
        /**
         * Publicar un evento
         * @description Lo usan los municipios y las oficinas de destino. El evento se suma al calendario y, si
         *     trae coordenadas, a las rutas de los polos que duermen o tienen algún lugar a 10 km o menos.
         *     No cambia qué polos se proponen ni en qué orden.
         *
         *     Publicar otra vez el mismo evento (mismo nombre, fechas, lugar y entidad) lo corrige: no lo
         *     duplica. La respuesta es el evento tal como lo verá el viajero.
         */
        post: operations["publicar_v1_eventos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/opciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Orígenes, intereses y rangos del formulario */
        get: operations["opciones_v1_opciones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/polos/{polo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ficha de un polo: recursos, clima mes a mes y eventos */
        get: operations["polo_v1_polos__polo_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado del servicio */
        get: operations["salud_v1_salud_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/viajes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hasta tres viajes para una consulta
         * @description La consulta viaja en la URL, igual que en el enlace para compartir: el motor es
         *     determinista, así que la misma consulta con la misma versión de datos da el mismo viaje.
         */
        get: operations["viajes_v1_viajes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Aviso */
        Aviso: {
            /** Mensaje */
            mensaje: string;
            /**
             * Nivel
             * @enum {string}
             */
            nivel: "info" | "advertencia";
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "estacionalidad" | "altitud" | "aclimatacion" | "presupuesto" | "acceso" | "dias" | "datos";
        };
        /**
         * Consulta
         * @description Lo que el viajero pide. Es también el enlace para compartir: el motor es
         *     determinista, así que la misma consulta con la misma versión de datos
         *     devuelve el mismo viaje.
         */
        Consulta: {
            /**
             * Altitud Max
             * @description Altitud máxima tolerada, en metros. Ninguna parada la supera.
             */
            altitud_max?: number | null;
            /**
             * Dias
             * @description Días disponibles en total, contando la ida y la vuelta desde el origen.
             * @default 6
             */
            dias: number;
            /**
             * Fecha Inicio
             * @description Día en que se sale del origen. Con ella los días del itinerario llevan fecha y los eventos se cruzan día a día; sin ella, se cruzan con el mes.
             */
            fecha_inicio?: string | null;
            /**
             * Intereses
             * @description Cero o más intereses. Sin intereses, el motor busca lo más valioso de cada polo.
             */
            intereses?: components["schemas"]["Interes"][];
            /**
             * Mes
             * @description Mes del viaje, 1 a 12. Obligatorio salvo que se dé fecha_inicio.
             */
            mes?: number | null;
            /**
             * Origen
             * @description Ciudad de partida, por su identificador (la lista está en /v1/opciones).
             * @default lima
             */
            origen: string;
            /**
             * Presupuesto
             * @description Soles por persona para todo el viaje. Ordena y advierte; no descarta rutas.
             */
            presupuesto?: number | null;
            /**
             * Sorpresa
             * @description Prioriza polos fuera del circuito habitual (término de novedad al máximo).
             * @default false
             */
            sorpresa: boolean;
        };
        /**
         * Costo
         * @description Una banda y no un precio: el motor estima, no vende.
         */
        Costo: {
            /**
             * Dentro Del Presupuesto
             * @description null si la consulta no trae presupuesto.
             */
            dentro_del_presupuesto?: boolean | null;
            /**
             * Desglose
             * @description Componentes del P50: transporte (con el tren y el bote), alojamiento, alimentación, entradas.
             */
            desglose?: {
                [key: string]: number;
            };
            /**
             * Exceso
             * @description Soles por encima del presupuesto, sobre el P50.
             */
            exceso?: number | null;
            /**
             * Moneda
             * @default PEN
             * @constant
             */
            moneda: "PEN";
            /** P20 */
            p20: number;
            /** P50 */
            p50: number;
            /** P80 */
            p80: number;
            /** Supuestos */
            supuestos?: string[];
        };
        /** Dia */
        Dia: {
            /** Fecha */
            fecha?: string | null;
            /**
             * Horas
             * @description Horas ocupadas entre traslados y visitas.
             */
            horas: number;
            /** Km */
            km: number;
            /** Nota */
            nota?: string | null;
            /** Numero */
            numero: number;
            /** Paradas */
            paradas?: components["schemas"]["Parada"][];
            /**
             * Tipo
             * @description ida_visita_y_vuelta (desde 1.1): un viaje de un día, que sale del origen y vuelve a él.
             * @enum {string}
             */
            tipo: "ida" | "visita" | "vuelta" | "ida_y_visita" | "visita_y_vuelta" | "ida_visita_y_vuelta";
        };
        /** Estacionalidad */
        Estacionalidad: {
            /** Dias Con Lluvia */
            dias_con_lluvia?: number | null;
            /** Explicacion */
            explicacion: string;
            /**
             * Horas Sol
             * @description Horas de sol por día, promedio del mes. null mientras no haya un dato confiable: el reanálisis no ve la neblina de la costa.
             */
            horas_sol?: number | null;
            /**
             * Lluvia Mm
             * @description Lluvia media del mes, diez años de datos.
             */
            lluvia_mm: number;
            /**
             * Mejores Meses
             * @description Los meses con mejor veredicto del polo, de menos a más lluvia: los viables o, si no hay ninguno, los de advertencia.
             */
            mejores_meses?: number[];
            /** Mes */
            mes: number;
            /** Temp Max C */
            temp_max_c?: number | null;
            /** Temp Min C */
            temp_min_c?: number | null;
            /**
             * Veredicto
             * @enum {string}
             */
            veredicto: "viable" | "advertencia" | "desaconsejado";
        };
        /** Evento */
        Evento: {
            /** Distrito */
            distrito: string;
            /** Fecha Fin */
            fecha_fin?: string | null;
            /** Fecha Inicio */
            fecha_inicio?: string | null;
            /**
             * Fuente
             * @enum {string}
             */
            fuente: "mincetur" | "publicado";
            /** Id */
            id: string;
            /** Nombre */
            nombre: string;
            /**
             * Precision Fecha
             * @description exacta: la fuente la publica. aproximada: calculada (santoral, cómputo de Pascua). por_confirmar: sin fecha conocida.
             * @enum {string}
             */
            precision_fecha: "exacta" | "aproximada" | "por_confirmar";
            /** Provincia */
            provincia: string;
            /** Publicado Por */
            publicado_por?: string | null;
            /** Region */
            region: string;
            /** Tipo */
            tipo?: string | null;
            /** Url */
            url?: string | null;
        };
        /**
         * EventoNuevo
         * @description Un evento que publica un municipio o una oficina de destino (RF-03).
         *
         *     Los textos se limpian antes de validarse: lo que se mide es lo que se va a mostrar.
         */
        EventoNuevo: {
            /** Descripcion */
            descripcion?: string | null;
            /** Distrito */
            distrito: string;
            /**
             * Fecha Fin
             * Format: date
             */
            fecha_fin: string;
            /**
             * Fecha Inicio
             * Format: date
             */
            fecha_inicio: string;
            /**
             * Lat
             * @description Dentro del Perú.
             */
            lat?: number | null;
            /**
             * Lon
             * @description Dentro del Perú.
             */
            lon?: number | null;
            /** Nombre */
            nombre: string;
            /** Provincia */
            provincia: string;
            /**
             * Publicado Por
             * @description Entidad que publica.
             */
            publicado_por: string;
            /** Region */
            region: string;
            /** Tipo */
            tipo?: string | null;
            /** Url */
            url?: string | null;
        };
        /** Eventos */
        Eventos: {
            /**
             * Desde
             * Format: date
             */
            desde: string;
            /** Eventos */
            eventos: components["schemas"]["Evento"][];
            /**
             * Hasta
             * Format: date
             */
            hasta: string;
            /**
             * Version Contrato
             * @default 1.2
             */
            version_contrato: string;
            /** Version Datos */
            version_datos: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Indicadores */
        Indicadores: {
            /** Altitud Max M */
            altitud_max_m?: number | null;
            /** Jerarquia Media */
            jerarquia_media?: number | null;
            /** Km Total */
            km_total: number;
            /** Paradas */
            paradas: number;
            /**
             * Paradas Jerarquia Alta
             * @description Paradas de jerarquía 3 o 4.
             */
            paradas_jerarquia_alta: number;
            /**
             * Valor Capturado
             * @description Parte del valor alcanzable del polo que el itinerario visita.
             */
            valor_capturado: number;
        };
        /**
         * Interes
         * @description Intereses del viajero, con su vocabulario y no con la taxonomía de MINCETUR.
         *     Cada uno se traduce a categorías, subtipos y actividades de la ficha oficial;
         *     la tabla de equivalencias es un artefacto del pipeline.
         * @enum {string}
         */
        Interes: "naturaleza" | "historia" | "gastronomia" | "caminatas" | "playa" | "fiestas" | "arquitectura" | "aventura";
        /** OpcionInteres */
        OpcionInteres: {
            /** Etiqueta */
            etiqueta: string;
            id: components["schemas"]["Interes"];
            /**
             * Paradas
             * @description Paradas posibles que atiende el interés en todo el inventario.
             */
            paradas: number;
        };
        /** OpcionOrigen */
        OpcionOrigen: {
            /**
             * Id
             * @description El valor que viaja en `origen`.
             */
            id: string;
            /** Nombre */
            nombre: string;
            /** Region */
            region: string;
        };
        /**
         * Opciones
         * @description Lo que la app necesita para armar el formulario sin fijar nada en su código.
         */
        Opciones: {
            altitud_max: components["schemas"]["Rango"];
            dias: components["schemas"]["Rango"];
            /** Intereses */
            intereses: components["schemas"]["OpcionInteres"][];
            /** Origenes */
            origenes: components["schemas"]["OpcionOrigen"][];
            presupuesto: components["schemas"]["Rango"];
            /**
             * Version Contrato
             * @default 1.2
             */
            version_contrato: string;
            /** Version Datos */
            version_datos: string;
        };
        /** Parada */
        Parada: {
            /** Km Desde Anterior */
            km_desde_anterior: number;
            /**
             * Llegada
             * @description Hora estimada de llegada, HH:MM.
             */
            llegada: string;
            /**
             * Minutos Traslado
             * @description Desde la parada anterior o desde la base.
             */
            minutos_traslado: number;
            /** Minutos Visita */
            minutos_visita: number;
            /**
             * Orden
             * @description Posición dentro del día.
             */
            orden: number;
            recurso: components["schemas"]["Recurso"];
        };
        /** Polo */
        Polo: {
            /** @description Dónde se duerme: el punto de partida de cada día. */
            base: components["schemas"]["Punto"];
            /**
             * Fuera Del Circuito
             * @description Ningún recurso del polo está en Lima ni en Cusco.
             */
            fuera_del_circuito: boolean;
            /** Id */
            id: number;
            /**
             * Nombre
             * @description Nombre legible del polo, armado con su localidad principal.
             */
            nombre: string;
            /**
             * Recursos
             * @description Recursos del inventario dentro del polo.
             */
            recursos: number;
            /**
             * Region
             * @description Región con más recursos del polo.
             */
            region: string;
            /** Regiones */
            regiones: string[];
        };
        /**
         * PoloDetalle
         * @description Ficha de un polo: sus recursos, su clima mes a mes y sus eventos del año.
         */
        PoloDetalle: {
            /** Atribucion */
            atribucion: string[];
            /**
             * Clima
             * @description Los doce meses, de enero a diciembre.
             */
            clima: components["schemas"]["Estacionalidad"][];
            /**
             * Eventos
             * @description Los acontecimientos del polo en los próximos doce meses.
             */
            eventos: components["schemas"]["Evento"][];
            polo: components["schemas"]["Polo"];
            /**
             * Recursos
             * @description Las paradas posibles del polo, de mayor a menor jerarquía.
             */
            recursos: components["schemas"]["Recurso"][];
            /**
             * Version Contrato
             * @default 1.2
             */
            version_contrato: string;
            /** Version Datos */
            version_datos: string;
        };
        /** Punto */
        Punto: {
            /** Altitud M */
            altitud_m?: number | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Nombre */
            nombre: string;
        };
        /** Rango */
        Rango: {
            /** Defecto */
            defecto?: number | null;
            /** Maximo */
            maximo: number;
            /** Minimo */
            minimo: number;
        };
        /**
         * Recurso
         * @description Un recurso turístico del inventario oficial, con lo que la ficha publica.
         */
        Recurso: {
            /** Altitud M */
            altitud_m?: number | null;
            /** Categoria */
            categoria: string;
            /**
             * Codigo
             * @description Código del recurso en el inventario de MINCETUR.
             */
            codigo: string;
            /** Descripcion */
            descripcion?: string | null;
            /**
             * Ingreso
             * @default desconocido
             * @enum {string}
             */
            ingreso: "libre" | "pagado" | "desconocido";
            /**
             * Jerarquia
             * @description Jerarquía oficial de 1 a 4. null cuando MINCETUR no la asigna («No aplica», «POR JERARQUIZAR»): nunca se imputa.
             */
            jerarquia?: number | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Nombre */
            nombre: string;
            /** Subtipo */
            subtipo?: string | null;
            /** Tarifa Soles */
            tarifa_soles?: number | null;
            /** Tipo */
            tipo: string;
            /**
             * Url Ficha
             * Format: uri
             * @description Ficha oficial: toda parada es verificable en la fuente (RNF-01).
             */
            url_ficha: string;
        };
        /** Respuesta */
        Respuesta: {
            /**
             * Atribucion
             * @description Fuentes y licencias que la app muestra junto al resultado.
             */
            atribucion: string[];
            /** @description La consulta tal como la entendió el motor. */
            consulta: components["schemas"]["Consulta"];
            /**
             * Rutas
             * @description Hasta tres polos distintos, del mejor al peor.
             */
            rutas: components["schemas"]["Ruta"][];
            /** @description Presente solo si no hay ninguna ruta: por qué y qué relajar. */
            sin_resultado?: components["schemas"]["SinResultado"] | null;
            /**
             * Version Contrato
             * @default 1.2
             */
            version_contrato: string;
            /**
             * Version Datos
             * @description Versión de los artefactos con que se calculó; va en el enlace.
             */
            version_datos: string;
        };
        /** Ruta */
        Ruta: {
            /** Avisos */
            avisos?: components["schemas"]["Aviso"][];
            costo: components["schemas"]["Costo"];
            /** Dias */
            dias: components["schemas"]["Dia"][];
            estacionalidad: components["schemas"]["Estacionalidad"];
            /** Eventos */
            eventos?: components["schemas"]["Evento"][];
            indicadores: components["schemas"]["Indicadores"];
            /**
             * Motivos
             * @description Por qué el motor propone este polo, en frases cortas.
             */
            motivos: string[];
            polo: components["schemas"]["Polo"];
            /** Puntaje */
            puntaje: number;
            traslado: components["schemas"]["Traslado"];
        };
        /** Salud */
        Salud: {
            /**
             * Estado
             * @default ok
             * @constant
             */
            estado: "ok";
            /** Version */
            version: string;
            /**
             * Version Contrato
             * @default 1.2
             */
            version_contrato: string;
            /**
             * Version Datos
             * @description null mientras el motor no tiene artefactos cargados.
             */
            version_datos?: string | null;
        };
        /** SinResultado */
        SinResultado: {
            /** Motivo */
            motivo: string;
            /** Sugerencias */
            sugerencias?: components["schemas"]["Sugerencia"][];
        };
        /** Sugerencia */
        Sugerencia: {
            /**
             * Campo
             * @enum {string}
             */
            campo: "origen" | "mes" | "fecha_inicio" | "dias" | "intereses" | "presupuesto" | "altitud_max";
            /**
             * Efecto
             * @description Qué cambia si se acepta, por ejemplo «aparecen 5 rutas».
             */
            efecto: string;
            /** Valor */
            valor: number | string | string[] | null;
        };
        /** Traslado */
        Traslado: {
            /**
             * Acceso
             * @description terrestre: se llega por carretera o en tren. sin_acceso_terrestre: la ida necesita bote.
             * @enum {string}
             */
            acceso: "terrestre" | "sin_acceso_terrestre" | "desconocido";
            /**
             * Desde
             * @description Nombre de la ciudad de origen.
             */
            desde: string;
            /**
             * Dias De Viaje
             * @description Días del viaje que se van en la ida y la vuelta.
             */
            dias_de_viaje: number;
            /**
             * Fuente
             * @description red_vial: calculado sobre la red de OpenStreetMap, con sus vías, trenes y botes. estimado: línea recta por un factor calibrado.
             * @enum {string}
             */
            fuente: "red_vial" | "estimado";
            /**
             * Horas
             * @description Horas de viaje de ida: por carretera, en tren o en bote.
             */
            horas?: number | null;
            /**
             * Medios
             * @description Con qué se hace la ida, en este orden: carretera, tren, bote (desde 1.2). En un viaje de un día, con qué se recorre el día.
             */
            medios?: ("carretera" | "tren" | "bote")[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    eventos_v1_eventos_get: {
        parameters: {
            query: {
                /** @description Primer día, AAAA-MM-DD. */
                desde: string;
                /** @description Último día, AAAA-MM-DD. Hasta un año después de `desde`. */
                hasta: string;
                /** @description Solo los de este polo. */
                polo?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Eventos"];
                };
            };
            /** @description No hay un polo con ese número. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La consulta no cumple el contrato. `detail` trae, por cada error, el `campo`, un `mensaje` en español y el `tipo`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El motor no tiene sus artefactos cargados. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    publicar_v1_eventos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventoNuevo"];
            };
        };
        responses: {
            /** @description El evento, como lo verá el viajero. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evento"];
                };
            };
            /** @description Falta la cabecera `X-Clave-Publicador` o la clave no es la correcta. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Este servidor no tiene una clave de publicador: no acepta publicaciones. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El evento no cumple el contrato, su región no es una del país, ya terminó o falta más de un año para que empiece. `detail` trae, por cada error, el `campo`, un `mensaje` en español y el `tipo`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El motor no tiene sus artefactos cargados, el evento no se pudo guardar o el calendario publicado está lleno. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    opciones_v1_opciones_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Opciones"];
                };
            };
            /** @description El motor no tiene sus artefactos cargados. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    polo_v1_polos__polo_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                polo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoloDetalle"];
                };
            };
            /** @description No hay un polo con ese número. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description El motor no tiene sus artefactos cargados. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    salud_v1_salud_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Salud"];
                };
            };
        };
    };
    viajes_v1_viajes_get: {
        parameters: {
            query?: {
                /** @description Ciudad de partida, por su identificador (la lista está en /v1/opciones). */
                origen?: string;
                /** @description Mes del viaje, 1 a 12. Obligatorio salvo que se dé fecha_inicio. */
                mes?: number | null;
                /** @description Día en que se sale del origen. Con ella los días del itinerario llevan fecha y los eventos se cruzan día a día; sin ella, se cruzan con el mes. */
                fecha_inicio?: string | null;
                /** @description Días disponibles en total, contando la ida y la vuelta desde el origen. */
                dias?: number;
                /** @description Cero o más intereses. Sin intereses, el motor busca lo más valioso de cada polo. */
                intereses?: components["schemas"]["Interes"][];
                /** @description Soles por persona para todo el viaje. Ordena y advierte; no descarta rutas. */
                presupuesto?: number | null;
                /** @description Altitud máxima tolerada, en metros. Ninguna parada la supera. */
                altitud_max?: number | null;
                /** @description Prioriza polos fuera del circuito habitual (término de novedad al máximo). */
                sorpresa?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Respuesta"];
                };
            };
            /** @description La consulta no cumple el contrato. `detail` trae, por cada error, el `campo`, un `mensaje` en español y el `tipo`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El motor no tiene sus artefactos cargados. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
